In [19]:
import numpy as np

from lesinput import lesinput
npunkt, punkt, nelem, elemkonn, tvsnitt = lesinput()

dim = npunkt

K = np.zeros((dim, dim))
print(K)
print(nelem)
print(elemkonn)

#for(i < nelem):

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
10
[[0 1]
 [1 2]
 [1 4]
 [2 3]
 [4 3]
 [5 4]
 [3 6]
 [4 7]
 [7 6]
 [8 7]]
